# Generated by Django 4.2.13 on 2024-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_market', models.IntegerField(choices=[(0, '深A'), (1, '沪A')], verbose_name='所属股市')),
                ('code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('name', models.CharField(max_length=20, verbose_name='股票名称')),
            ],
            options={
                'verbose_name': '股票信息',
                'verbose_name_plural': '股票信息',
            },
        ),
    ]
